spring:
  application:
    name: spring-cloud-yzx-client
server:
  port: 5200
  context-path: /client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5000/eureka/
  instance:
    prefer-ip-address: true